### PR TITLE
Zalvures

### PR DESCRIPTION
**Pull request by Zalvures**

### CODE REVIEW

**Review by kii-dot — APPROVED** [review]
Looks good

**Comment by kii-dot** [comment]
SigmaProp and Bracket within the contract. 

{
    sigmaProp((pkA && HEIGHT <= deadline) || (pkB && HEIGHT > deadline))
}

**Comment by kii-dot** [comment]
Everything else looks good

**Comment by K-Singh** [comment]
Okay ngl, I didn't see that those last two commits were added, just saw that the branch was approved. Anyways, everything actually looks pretty good, just had a few small typos like coll vs Coll for the types and having an extra bracket or two where there shouldn't be one.

**Comment by K-Singh** [comment]
The blockchainSim part was a little confusing. It's ErgoScript, so just use HEIGHT like you did in the other statements. Other than that the SigmaProp looked perfect and made sense.

**Pull request merged**
